### ISSUE TITLE
Reading assignment1 

### ISSUE THREAD

**Issue by oztasozgurcan** [bounswe/bounswe2019group4#1]
Everyone reads the [assignment1](https://github.com/bounswe/bounswe2019group4/blob/master/wiki-assets/assignments/Assignment1.pdf) until the first meeting.

- [x] Ege Başural
- [x] Emre Demircioğlu
- [x] Bahadır Hocamoğlu
- [x] Muhammed Bera Kaya
- [x] Gürkan Demir
- [x] Baturalp Yörük
- [x] Taha Eyüp Korkmaz
- [x] Elif Çalışkan
- [x] İbrahim Özgürcan Öztaş
- [x] İsmail Levent Baş

**Comment by gurkandemir** [comment]
After reading first assignment check your name from the list above and also, the student who will check last may close this issue.
