### ISSUE TITLE
Deliverables for Milestone2

### ISSUE THREAD

**Issue by EmreDemircioglu** [bounswe/bounswe2019group4#109]
prepare list, status and evalution of deliverables for Milestone2

**Comment by muhammed-kaya-2016400234** [comment]
I evaluated the "Project Plan"  deliverable. It might need some contribution.

**Comment by oztasozgurcan** [comment]
I've added the evaluations of the deliverables "Implementation" and "API Documentation".

**Comment by oztasozgurcan** [comment]
All changes are added to the Milestone2. Issue closed.
