### ISSUE TITLE
Summary of work done

### ISSUE THREAD

**Issue by EmreDemircioglu** [bounswe/bounswe2019group4#110]
write individual summary of work done part for Milestone2

**Comment by gurkandemir** [comment]
- [ ] Bahadir,
- [ ] Baturalp,
- [ ] Bera,
- [ ] Ege,
- [ ] Elif,
- [ ] Emre,
- [ ] Gurkan,
- [ ] Levent,
- [ ] Ozgurcan,
- [ ] Taha
