### ISSUE TITLE
Create sequence diagrams for API

### ISSUE THREAD

**Issue by EmreDemircioglu** [bounswe/bounswe2019group4#113]
- [x] Sign up sequence diagram for API front end.
- [x] View Events page sequence diagram for API front end.
- [x] Currency converter usage sequence diagram for API front end.

**Comment by baturalp-yoruk** [comment]
I think it is all good. Nice job 👍

**Comment by bahadirh** [comment]
> I think it is all good. Nice job 👍

As the diagrams are done and reviewed, I'm closing thatt issue for now.
