### ISSUE TITLE
initialize frontend folder of the project

### ISSUE THREAD

**Issue by bahadirh** [bounswe/bounswe2019group4#126]
The frontend side of the project requires some initial setup related to react, react-router and redux. After those are satisfied, the team may start the actual implementation of pages.

**Comment by ege-basural** [comment]
I initialized it, redux, router and react is working properly, I also designed a header to get us started but it needs some visual modifications, also I have trouble connecting to AWS, so I couldn't make it live at the moment.

**Comment by ege-basural** [comment]
@bahadirh you worked with AWS, maybe you could help us

**Comment by bahadirh** [comment]
I've published the latest version of our website. I consider that issue is resolved.
