### ISSUE TITLE
Create the database

### ISSUE THREAD

**Issue by bahadirh** [bounswe/bounswe2019group4#128]
We have decided to use Mongo as database our database. An instance of MongoDB should be started and connected to the backend.

**Comment by gurkandemir** [comment]
We need to divide database into two according to environment. It must connect to test database while we are developing some features, however for deployed version it must use database with real inputs.

**Comment by bahadirh** [comment]
> We need to divide database into two according to environment. It must connect to test database while we are developing some features, however for deployed version it must use database with real inputs.

Initiated another database instance for testing purposes.
