### ISSUE TITLE
Add register via Google accounts.

### ISSUE THREAD

**Issue by cemalaytekin** [bounswe/bounswe2019group4#129]
As we indicate in the requirements analysis

>  1.1.1.4.6: Users shall be able to register via their Google accounts.

we should provide sign-up and sign-in via Google Account

**Comment by ege-basural** [comment]
[Instructions for Google Sign Up](https://developers.google.com/identity/sign-in/web/sign-in)
We should work together as frontend and backend for this issue, maybe discuss more and get a more rigid plan for it in the next meeting?

**Comment by gurkandemir** [comment]
It would be better to continue together, since we have some problems in integrating Google.
