### ISSUE TITLE
Web UI Framework

### ISSUE THREAD

**Issue by ege-basural** [bounswe/bounswe2019group4#131]
We need to decide on a UI framework.
[Argon](https://demos.creative-tim.com/argon-design-system-react/#/) or [Semantic](https://react.semantic-ui.com) seems fine to me, do you have any other suggestions, or any comment on which to pick?

**Comment by tahakorkmaz14** [comment]
While I didn't use it before but after research I found Material, Bootstrap, Semantic and Argon are most popular ones. We can choose by your suggestion it's fine for me

**Comment by muhammed-kaya-2016400234** [comment]
I don’t have an idea of this.You are the most experienced one among us.You can decide.

**Comment by ege-basural** [comment]
I guess we could stick on Semantic at the moment, I am most familiar with it among these, we could maybe change later, if it doesn't satisfy us.
