### ISSUE TITLE
Frontend Feature Sıgn In

### ISSUE THREAD

**Issue by ege-basural** [bounswe/bounswe2019group4#137]
Sign in page should be initialize, maybe we could make a modal instead of a new page for this?

**Comment by gurkandemir** [comment]
Back-end part of sign in is already ready. Here is the scenario:

- Post request to api.dev.arkenstone.ml/auth/login with email and password in body.
- We response according to given fields.

**Comment by ege-basural** [comment]
Frontend development is completed, PR waiting.
