### ISSUE TITLE
Frontend Feature Sign Up

### ISSUE THREAD

**Issue by ege-basural** [bounswe/bounswe2019group4#138]
We should initialize a sign up page.

**Comment by gurkandemir** [comment]
Back-end part of signup is already ready. Here is the scenario:

- Post request to api.dev.arkenstone.ml/auth/signup with name, surname, email, password, location, isTrader, isPublic in body.
    1. Name, surname, email, password, location is string.
    2. isTrader is boolean which specifies whether user is trader or basic. True means user is trader.
    3. isPublic is boolean which specifies whether user has public profile or not. True means user has public profile.
- If user is trader, we also need some extra fields about tckn and iban which are also string.
- We response according to given fields.

**Comment by ege-basural** [comment]
done, waiting for PR.
