### ISSUE TITLE
Update project description part in readme

### ISSUE THREAD

**Issue by gurkandemir** [bounswe/bounswe2019group4#14]

**Comment by gurkandemir** [comment]
we have to describe project in more detail, and also project description file was added twice; one of them must be deleted

**Comment by tahakorkmaz14** [comment]
oh my i didn't realize the description was already added

**Comment by bahadirh** [comment]
Some comments on the purpose of the project and the issues it solves might be added, just to give the visitor a general idea of what the project is about.

**Comment by bahadirh** [comment]
Also, while you're at it, the subsection 'who are we?' might be changed to 'who we are'.
