### ISSUE TITLE
Frontend Feature Reset Password

### ISSUE THREAD

**Issue by ege-basural** [bounswe/bounswe2019group4#140]
Backend is ready @bahadirh @gurkandemir @cemalaytekin  correct me if I'm wrong. We should make a reset password page, and put in in proper place, I guess sign in page. 
First sign in page should be made.

**Comment by gurkandemir** [comment]
Back-end part of reset password is already ready. Email infrastructure is done. We will talk about it in the meeting but let me summarize the scenario:

- There must be a **Forget password?** button in the login page.
- When user clicks on it, it must be redirected to another page where user can fill his own email address.
- When user enters his email address, you should request api.dev.arkenstone.ml/auth/forget-password with email in body.
- We send an email to user which contains reset password link. In this link, we redirect user to frontend part. So you have to implement an extra page, where user can enter his new password. URL must be ...../auth/reset-password/:token . Token is supplied from us. 
- Then using that token and password, you must request api.dev.arkenstone.ml/auth/reset-password with token and password in body.
- Finally we change user's password.
