### ISSUE TITLE
Frontend Readme

### ISSUE THREAD

**Issue by ege-basural** [bounswe/bounswe2019group4#141]
We should configure Readme.md.

**Comment by tahakorkmaz14** [comment]
Should I add a new readme for frontend only? I'll add the frontend meeting notes later.

**Comment by bahadirh** [comment]
Any update on that issue?

**Comment by leventbass** [comment]
I updated the frontend README.md to include the command `npm install` before `npm start` as it gave an error because of the lack of node modules. For now, I can close this issue.
