### ISSUE TITLE
Add Swagger to backend endpoints

### ISSUE THREAD

**Issue by ege-basural** [bounswe/bounswe2019group4#145]
If you guys could set up swagger, it would be really helpful for us.

**Comment by cemalaytekin** [comment]
@bahadirh @gurkandemir what is the final decision about this issue? We are going to use postman right? If so, we can close this issue!

**Comment by bahadirh** [comment]
> what is the final decision about this issue? We are going to use postman right? If so, we can close this issue!

I guess so. The API documentation can be found [here](https://documenter.getpostman.com/view/3191118/SVtTz9Pn?version=latest). It looks incomplete, and it is actually, but we will update it soon.

The link will be added to our wiki page as well.
