### ISSUE TITLE
Arranging a customer meeting to clarify the preliminary requirements

### ISSUE THREAD

**Issue by oztasozgurcan** [bounswe/bounswe2019group4#16]
To be able to create a crystal clear preliminary requirements, we've to arrange a meeting with our customer.

**Comment by bahadirh** [comment]
sent an email to our customer, asking for a meeting to discuss the requirements.

**Comment by bahadirh** [comment]
the questions might be asked in the PS hour on Friday, no additional meeting will be arranged.

**Comment by elif-caliskan** [comment]
Questions have been asked in PS hour.
