### ISSUE TITLE
Adding Validation to Our Models 

### ISSUE THREAD

**Issue by cemalaytekin** [bounswe/bounswe2019group4#175]
It would be super cool and useful to add validation functions to models instead of implementing them outside of the models such that:

- [x] If google id exists, then password is not required. 
- [x] password length check
- [x] common password check

and so on. Feel free to add some other validations.

[Vaildation documentation](https://mongoosejs.com/docs/validation.html#update-validators-and-this) might be useful for better understanding.

**Comment by gurkandemir** [comment]
- [] iban,
- [] tckn
