### ISSUE TITLE
Update website theme

### ISSUE THREAD

**Issue by bahadirh** [bounswe/bounswe2019group4#246]
It would be better if we update our website theme with a more modern and stylish one. [That one](https://react.semantic-ui.com/layouts/homepage), from the examples of the UI framework we use, Semantic-UI, looks good.

**Comment by leventbass** [comment]
As I have re-designed our mobile application using the color palette from the website @bahadirh had suggested, it would be nice if our web and mobile applications both look similar in terms of the themes used. Any update on this issue?

**Comment by leventbass** [comment]
We will continue designing Arkenstone website so that it is in synch with our mobile application in terms of its theme.

**Comment by tahakorkmaz14** [comment]
We used @leventbass s design on the website overall and it looks splendit
