### ISSUE TITLE
Add informative content to the homepage

### ISSUE THREAD

**Issue by bahadirh** [bounswe/bounswe2019group4#249]
Our homepage looks too shallow. Some informative content that helps registered users use the system or attracts new ones might be added there.

**Comment by leventbass** [comment]
We will continue adding necessary information to our homepage so that potential Arkenstone users will know what our system has to offer before they sign up. We will also try to design the homepage to match with the current design of our mobile application.

**Comment by tahakorkmaz14** [comment]
With @leventbass s additions to mine it looks okey
