### ISSUE TITLE
Android Add Article Feature

### ISSUE THREAD

**Issue by EmreDemircioglu** [bounswe/bounswe2019group4#268]
Implement article feature for view or creating new article and make its connections to other pages.

**Comment by leventbass** [comment]
It seems that the new design for our layouts will take more time than we have anticipated before. Hence, I need someone to take over and continue implementing article feature where I left off.

**Comment by EmreDemircioglu** [comment]
I can continue the article implementation

**Comment by leventbass** [comment]
Thanks to @EmreDemircioglu our implementation of the article functionality was done. After he handled the functionality, I designed the necessary layouts to make the article related screens look nice and in accord with our theme.
