### ISSUE TITLE
Backend Delete Relations

### ISSUE THREAD

**Issue by cemalaytekin** [bounswe/bounswe2019group4#280]
We are deleting specific instances from database in some situations such that user wants to delete his/her article, comment or etc. For example, in the article feature, we are just deleting the given article instance from article model. We also need to delete the corresponding instance from article-user model. Same for the comment and other cases. 

I implemented this for the portfolio feature. We can check deletePortfolio function.

**Comment by gurkandemir** [comment]
I am on it.
