### ISSUE TITLE
Backend Bug Report trading-equipment

### ISSUE THREAD

**Issue by EmreDemircioglu** [bounswe/bounswe2019group4#282]
trading-equipments/usd endpoint returns JsonArray instead of single JsonObject at "current" field. Since it is in a specific currency it can only have one current value object. This affects deserializaton of json at the android part.

**Comment by gurkandemir** [comment]
It returns an array with size 1 for all currencies. You can use array's first element.

If it is a problem again, we will fix it.

**Comment by EmreDemircioglu** [comment]
I know but it also creates memory leak in the android. Turning it to a single object is a better solution.

**Comment by gurkandemir** [comment]
I am working on it.
