### ISSUE TITLE
Frontend Portfolios

### ISSUE THREAD

**Issue by gurkandemir** [bounswe/bounswe2019group4#292]
According to our requirements:
* User shall have at least one portfolio
* User shall be able to have different portfolios
* User shall be able to rename portfolio
* Users shall be able to add or remove trading equipments from/to portfolio.
* User shall be able to share portfolio in profile page
* Other users shall be able to follow other user's portfolio.
* Users shall be able to create/delete their portfolios.

For more details about endpoints, you can get contact with backend team or use api documentation.

**Comment by tahakorkmaz14** [comment]
Done
