### ISSUE TITLE
Frontend Articles

### ISSUE THREAD

**Issue by gurkandemir** [bounswe/bounswe2019group4#293]
According to our requirements:
* User shall be able to share ideas about trading equipment as articles .
* User shall be able to comment on articles.
* User shall be able to rate articles.

For more details about endpoints, you can get contact with backend team or use api documentation.

**Comment by muhammed-kaya-2016400234** [comment]
Functionalities and pages related to articles has been implemented. The links to article details page should be added to profile page of authors.

**Comment by tahakorkmaz14** [comment]
Links are added
