### ISSUE TITLE
Other Users' Page Link

### ISSUE THREAD

**Issue by tahakorkmaz14** [bounswe/bounswe2019group4#297]
What should be the link of the other users? Instead of showing their id, is " /name_surname" okay? Then, what should be the link in case of when we two users have the same name,surname?

**Comment by bahadirh** [comment]
It has been decided and implemented already. `/profile/:userId` is implemented for that purpose. Further details can be found in our <a href="https://documenter.getpostman.com/view/3191118/SW7Xa9Vu?version=latest" target="_blank">Postman docs</a>, which can be imported using <a href="https://www.getpostman.com/collections/32449789063bd3730e28" target="_blank">that link</a>.
