### ISSUE TITLE
Add request body validation to the endpoints accepting POST requests

### ISSUE THREAD

**Issue by bahadirh** [bounswe/bounswe2019group4#302]
Our API can be enhanced with more usage of request body validation middleware wherever possible. We can check our endpoints and do necessary changes in `backend-enhancement-body-validation` branch.

- [x] article endpoints
- [x] comments endpoints
- [x] events endpoints
- [x] authentication endpoints
- [x] portfolio endpoints
- [x] profile endpoints
- [x] trading equipments endpoints

**Comment by gurkandemir** [comment]
Not only post methods, but also patch methods must be updated. I will be working on it.
