### ISSUE TITLE
Requirements Feedback 

### ISSUE THREAD

**Issue by cemalaytekin** [bounswe/bounswe2019group4#330]
According to customer's requirements feedback, @gurkandemir @bahadirh and I reviewed and fixed those requirements that are not clear, gramatically wrong or have missing parts. But we have confusion about the following 3 requirement feedbacks. We could not decide what reaction we should take for them? We need your opinions. Also if you review the other requirements indicated in the feedback, it would be nice. 

- [x] 1.2.2.3 how about buy order?
- [x] 1.2.3.3 as far as I understand, only events have significance level. How are you planning to sort articles, users, and trading equipments by their significance level? Also, what are you planning to do if their significance level is same and they have no location?
- [x] 1.2.4.2 based on which metric?

**Comment by bahadirh** [comment]
I've updated the requirements and clarified the vague parts of it.
