### ISSUE TITLE
Readme Mobile part

### ISSUE THREAD

**Issue by EmreDemircioglu** [bounswe/bounswe2019group4#338]
- In order to run mobile application on a computer, people need to have an android emulator(Google pixel or equivalent) 
- Just gradle build command is not enough, gradle bootrun command is also required to run mobile application
- And the minimum android version, that is supported, is Android 6.0 (Marshmallow)

**Comment by leventbass** [comment]
Thank you for your insight, I will close this issue since I already started updating README page and mobile README will also be a part of it.
