### ISSUE TITLE
Backend Current Stock Value Update Bug

### ISSUE THREAD

**Issue by cemalaytekin** [bounswe/bounswe2019group4#361]
The scheduler does not update the current value of stocks. It creates a new instance with the new value. It should not create a new instance. It should update the 'rate' attribute of the stock if it is already exists in the database. If it does not exist, then it should create a new instance

**Comment by gurkandemir** [comment]
We can close this issue, we have merged related pull request with backend-dev and deployed necessary changes. Now, it works as we expected. @cemalaytekin
