### ISSUE TITLE
Bug Report trading equipment

### ISSUE THREAD

**Issue by EmreDemircioglu** [bounswe/bounswe2019group4#366]
/trading-equipments endpoint returns 2 types of date formats. This causes json parse error on android side.

**Comment by gurkandemir** [comment]
Probably, it is occurred in current trading equipments page. Due to the fact that 3rd API gives us response in a such way, we have 2 different day format.

But now I am working, on it to fix this. Date format must be in a single type, and it is in type "yyyy-mm-dd hh:mm:ss"
