### ISSUE TITLE
Frontend enhancement real time notifications 

### ISSUE THREAD

**Issue by muhammed-kaya-2016400234** [bounswe/bounswe2019group4#403]
We can make the new notifications appear on the user screen. For this purpose, notifications might have a field which indicates if it is seen by the user before or not. On the frontend side, we can check for the unseen notifications over and over with some time interval.

**Comment by gurkandemir** [comment]
Added new field named **seen** which has default value false to notification model. Implemented new endpoint which is ** POST /notifications ** which makes notification seen status true.

**Comment by muhammed-kaya-2016400234** [comment]
Frontend part is also done. Waiting for PR( #405 )
