### ISSUE TITLE
Rewrite persona2 and expand persona1 and 3

### ISSUE THREAD

**Issue by gurkandemir** [bounswe/bounswe2019group4#42]
Check feedback for assignment3, number 4&5

**Comment by gurkandemir** [comment]
Related feedbacks: 
**'Find a different story for Valentin Yılmaz. You can make parody personas such as Group 1 did with Broker Bilo, but persona should be strongly related with the project. Also, you will make presentation next semester by using the defined personas, so they should be appropriate to present.'**

**'My advice for personas is to rewrite all three from scratch, or rewrite persona 2 and expand persona 1 and 3. '**

**Comment by tahakorkmaz14** [comment]
ReWrote the persona 2 and expanded the 1 and 3
