### ISSUE TITLE
Make prediction rate for specific trading equipment in mockups

### ISSUE THREAD

**Issue by gurkandemir** [bounswe/bounswe2019group4#43]
Check feedback for assignment3, number 7

- [x] Gurkan
- [x] Elif

**Comment by gurkandemir** [comment]
- [ ] Gurkan
- [ ] Elif

**Comment by gurkandemir** [comment]
Related feedback: **'The type of trading equipment should be specific for prediction success ratio (e.g., BIST100 prediction success ratio).'**

**Comment by elif-caliskan** [comment]
> Check my update about prediction rate, if it is ok for you, you can apply same design for android

I think in search bar you can change it with "Prediction Rates for: EUR/USD: High to Low". Other than that, I followed the same procedure.

**Comment by gurkandemir** [comment]
Done.
