### ISSUE TITLE
Revise sequence diagrams after feedback

### ISSUE THREAD

**Issue by gurkandemir** [bounswe/bounswe2019group4#49]
- [x] Baturalp Yoruk: 
"In sign up sequence diagram, guest user sends a method to system, however, there is no connection between guest user and system in class diagram. You should somehow connect these two classes. Same applies for the rest of sequence diagrams."
- [x] Bahadır Hocamoglu:
"In comment on a trading equipment sequence diagram, you use comment() method. However, as far as I can see, there is no method called comment() in your class diagram. Also, input parameters for addComment() method is different in sequence diagram compared to the class diagram. Moreover, you should define alt to show different scenarios (i.e., success or failure)."
- [x] Emre Demircioglu: 
"In add stop/loss sequence diagram, you have addStopLoss() method. However, you don't have such method in your class diagram."
- [x] Elif Caliskan:
"In manual addition to profit loss diagram, what is create" 
- [x] Gurkan Demir:
"In follow other users sequence diagram, you have UI Class. However, there is no class named UI in sequence diagram. Same applies for Database. Also, the else for the first alternative (outer) is not actually the else version of the first alternative. Also, it does not make sense to have two methods, named, acceptRequest() and rejectRequest(), seperately. Simply, define one method which will return a boolean. 0 means reject (or accept) and 1 means accept (or reject). Also, user2.follower.push->user2.followers.push."
- [x] Ozgurcan Oztas:
"In edit portfolio trading equipment, you have adTradingEquipment() method, which I cannot find in your class diagram. Also, you don't have a class in your class diagram called DataBase. Also, for the second alternative, you wrote Else, but for the first one, you didn't. Be compatible."
- [x] Muhammed Bera Kaya:
"In make investment sequence diagram, there is a connection between Transaction and System class, which does not exist in class diagram. What is <create> and transaction."
- [x] Taha Eyup Korkmaz:
"In search and sort users, there is a method called search(), which I cannot find in your class diagram. Also, again, there is no connection between Search Engine class and System class in your class diagram. No sort() and sortByPrediction() methods in class diagram."

**Comment by elif-caliskan** [comment]
As discussed in the meeting, the arrows should represent the methods of pointed classes, we should keep this in mind while revising.  Additionally, make sure the used methods that belong to a class also exist in class diagram.

**Comment by gurkandemir** [comment]
Method named _**addComment**_ takes type **Comment** as parameter, not **text**. Therefore, first you have to create comment, then give it as a parameter for that method. @bahadirh

**Comment by bahadirh** [comment]
> Method named _**addComment**_ takes type **Comment** as parameter, not **text**. Therefore, first you have to create comment, then give it as a parameter for that method. @bahadirh

added class names for clarification

**Comment by gurkandemir** [comment]
> 
> 
> > Method named _**addComment**_ takes type **Comment** as parameter, not **text**. Therefore, first you have to create comment, then give it as a parameter for that method. @bahadirh
> 
> added class names for clarification

You have to push that comment into that trading equiment's comments list

**Comment by gurkandemir** [comment]
Sort part of sequence must be done if user list is not empty. It is meaningless to sort empty list, so you have to carry sort part to if clause. @tahakorkmaz14
