### ISSUE TITLE
Review class diagrams after feedback

### ISSUE THREAD

**Issue by gurkandemir** [bounswe/bounswe2019group4#50]
Related feedbacks about class diagram:
- "In class diagram, you don't have Google Maps class, but you assume you have such class (e.g., check signUp method)."
- "In class diagram, what are the input parameters for logOut() method?"
- "In class diagram, for iban and tc variables, are you sure that defining iban and tc as integer will be sufficient?"
- "In class diagram, for defining the relations, you can use words such as has, writes, follows other than extends"
- "In class diagram, recomendation->recommendation"
- "In class diagram, try to find relations for unbounded classes. For example, user can set alert (or follow, depending on your choice) and get notification for certain events."
- "In class diagram, Trading Equipment->TradingEquipment"
- "In class diagram, how about defining a symbol variable for currency, crypto etc."
- "In class diagram, for Transaction class, the type of buyEquipment and sellEquipment should be TradingEquipment."

**Comment by elif-caliskan** [comment]
We made some improvements about every feedback except for the logOut() method's parameters. 

- Changed the type of iban and tc variables' type to string. 
- Changed the type of map variable to string.
- Added the relations between classes such as has, writes, follows...
- Fixed the typos.
- Defined symbol variables to currency and cryptocurrency.
- Changed some types of parameters.

**Comment by gurkandemir** [comment]
In my opinion, user class must have variable named **_id_** which is **integer**. Every user must have **unique** id, and we can use that variable as a parameter for method named **_logOut()_**. Additionally, **_logOut(int id)_** must return boolean which indicates whether the action was succesful or not.

**Comment by elif-caliskan** [comment]
Thank you for the feedback, changed the diagram accordingly. 

> In my opinion, user class must have variable named **_id_** which is **integer**. Every user must have **unique** id, and we can use that variable as a parameter for method named **_logOut()_**. Additionally, **_logOut(int id)_** must return boolean which indicates whether the action was succesful or not.

**Comment by gurkandemir** [comment]
Moreover, it would be better if sort methods in search engine take 2 parameters, not only one. One for list to be sorted, the other one for criteria for sorting. Also, those methods must return sorted list. I will update class diagram according to this.
