### ISSUE TITLE
Prepare 'executive summary' part for Milestone1

### ISSUE THREAD

**Issue by gurkandemir** [bounswe/bounswe2019group4#52]
Our Milestone report must include **executive summary**(_summary of project status and any changes that are planned for moving forward_)

**Comment by gurkandemir** [comment]
We need to expand it, it is really simple with this version

**Comment by elif-caliskan** [comment]
We can add Project Introduction, Work Done and Plans sections for the summary in order to clearly explain the process of our project. We can go through this [report](https://github.com/bounswe/bounswe2018group5/blob/master/plan/cmpe-352-report.pdf).

**Comment by elif-caliskan** [comment]
Added Project Introduction part you can give feedbacks about the first part. For the "Work Done So Far" part we can scan the meeting notes.

**Comment by elif-caliskan** [comment]
> Added Project Introduction part you can give feedbacks about the first part. For the "Work Done So Far" part we can scan the meeting notes.
Contributed to "Work Done So Far" and "Planned Changes" parts. Open for any feedbacks -especially the Planned Changes section should be reviewed since some plans might've been forgotten-
