### ISSUE TITLE
Prepare 'deliverables' part for Milestone1

### ISSUE THREAD

**Issue by gurkandemir** [bounswe/bounswe2019group4#53]
Our Milestone report must include:
* list and status of **deliverables**
* evaluation of the **status** of deliverables and its impact on your project plan

**Comment by bahadirh** [comment]
added list of deliverables and evaluation of them. Now it requires review by other assignees.

**Comment by gurkandemir** [comment]
It would be better if we evaluate deliverables in much detail.

**Comment by gurkandemir** [comment]
We can insert a new coloumn named **“Deadlines”** to table in section2.

**Comment by bahadirh** [comment]
> It would be better if we evaluate deliverables in much detail.

added subsections for each deliverable


> We can insert a new coloumn named **“Deadlines”** to table in section2.

fixed
