### ISSUE TITLE
Prepare 'summary of work done' for Milestone1

### ISSUE THREAD

**Issue by gurkandemir** [bounswe/bounswe2019group4#54]
Our Milestone report must include a summary of work done by each team member(in tabular format)

- [x] Bahadır Hocamoglu
- [x] Baturalp Yoruk
- [x] Elif Caliskan
- [x] Emre Demircioglu
- [x] Ege Basural
- [x] Gurkan Demir
- [x] Ibrahim Ozgurcan Oztas
- [x] Muhammed Bera Kaya
- [x] Taha Eyup Korkmaz

**Comment by bahadirh** [comment]
We have done some of the work together, ie. requirements, user personas and stories, some of the sequence diagrams. It would be good to add one paragraph listing those parts of the work.
