### ISSUE TITLE
Prepare other parts of Milestone1

### ISSUE THREAD

**Issue by gurkandemir** [bounswe/bounswe2019group4#55]
Our Milestone report must include:
* [x] _Communication plan,_

* **Requirements:**
 - [x] _Glossary,_
 - [x] _Functional requirements,_
 - [x] _Nonfunctional requirements,_
* **Mockups:**
 - [x] _Mockup1,_
 - [x] _Mockup2,_
 - [x] _Mockup3,_
 - [x] _Persona1,_
 - [x] _Persona2,_
 - [x] _Persona3,_
* **Design:**
 - [x] _Usecase diagram,_
 - [x] _Class diagram,_
 - [x] _Sequence diagrams_

**Comment by gurkandemir** [comment]
I generally added all those things listed above to our milestone report. Can you review my work done, and give me feedback about template? @oztasozgurcan

**Comment by oztasozgurcan** [comment]
@gurkandemir  Sorry for the delay, I've just finished reviewing the document. The template seems well organized and it seems magnificent. Thanks for your effort.
