### ISSUE TITLE
Create project logo

### ISSUE THREAD

**Issue by bahadirh** [bounswe/bounswe2019group4#57]
Our project, Arken, needs a logo. Some recommendations were discussed in meeting, nothing specific is decided though. That logo will be used almost everywhere in the project, website and mobile app. So it should be something catchy :)
The deadline is April, 11th @11.00pm.

**Comment by oztasozgurcan** [comment]
Deadline is not here in this explanation. Can I be informed about that?

**Comment by bahadirh** [comment]
> Deadline is not here in this explanation. Can I be informed about that?

updated the description

**Comment by oztasozgurcan** [comment]
> > Deadline is not here in this explanation. Can I be informed about that?
> 
> updated the description

Thanks.
