### ISSUE TITLE
Create own wiki page

### ISSUE THREAD

**Issue by gurkandemir** [bounswe/bounswe2019group4#6]
- [x] Bahadır Hocamoğlu
- [x] İsmail Levent Baş
- [x] Ege Başural
- [x] Baturalp Yörük
- [x] Taha Korkmaz
- [x] Elif Çalışkan
- [x] Gürkan Demir
- [x] Emre Demircioğlu 
- [x] Özgürcan Öztaş
- [x] Muhammed Bera Kaya

**Comment by bahadirh** [comment]
@leventbas92 after creating your page, please make your name in the wiki sidebar a link to your page.
