### ISSUE TITLE
Implement login endpoint

### ISSUE THREAD

**Issue by bahadirh** [bounswe/bounswe2019group4#76]
Registered users should be able to login to the system and get session data to identify themselves when performing user-specific operations. Session implementation details are not specified yet.

**Comment by bahadirh** [comment]
We can use [cookie-session](https://expressjs.com/en/resources/middleware/cookie-session.html) or some other helper libraries to store user data as sessions on client side or server side.

**Comment by bahadirh** [comment]
Created a branch from backend for that issue.

**Comment by bahadirh** [comment]
The file secrets.js is updated. The latest version can be found at general channel on Slack.

**Comment by gurkandemir** [comment]
Merged with master.
