### ISSUE TITLE
View events endpoint

### ISSUE THREAD

**Issue by bahadirh** [bounswe/bounswe2019group4#81]
The user isn't required to be logged in to use that endpoint. It's supposed to respond with a list of events, only titles should suffice it.

**Comment by bahadirh** [comment]
Currently, the endpoint doesn't handle errors from external API. It would be good if we handle that case before closing that issue.

**Comment by gurkandemir** [comment]
i will work on it.

**Comment by gurkandemir** [comment]
done.
